### PR TITLE
Fixed cascade logic for dropdown options filtering

### PR DESCRIPTION
**Pull request by brandonzhu09**
## Description

Bugfix for improper cascading logic when listing the valid dropdown options in the data viewer. Resolved this issue by applying the correct number of filters at each update option event in the backend.

Resolves issue GEOS-ESM/evagram_input#9.

image

As shown in the image, there are no longer groups that do not belong to the variable as well as the owner, experiment, and observation associated with it.

### CODE REVIEW

**Comment by asewnath** [comment]
Hi Brandon, I'm working on testing the updates to evagram and I've found that I'm able to view an experiment name even though I haven't selected a User. Are you also getting this behavior?

Screenshot 2024-07-22 at 10 57 17 AM

**Comment by brandonzhu09** [comment]
> Hi Brandon, I'm working on testing the updates to evagram and I've found that I'm able to view an experiment name even though I haven't selected a User. Are you also getting this behavior?
> 
> Screenshot 2024-07-22 at 10 57 17 AM

Yes, I just noticed that I have been getting this behavior as well, but I found where the issue was in the initial load of the page and have fixed the bug.

**Comment by asewnath** [comment]
After killing pg4admin processes I had on port 5432 and then running docker-compose.yaml (my local database is now able to use 5432:5432) and then running evagram-input, I'm able to see the new input data. Bugfix works on my end. Excellent work!

**Review by ghost — COMMENTED** [review]
A few overall comments that may not be immediately relevant to the bugfix:

1)  First of all, great work on fixing this bug!
2)  Please add """ docstrings to every function.
3)  Some of the functions here are helpers, not "views" themselves.  Namely everything from `get_owners` and beyond.  Would it be appropriate to import them from a new `util` module?  I want to keep the `views` as minimal as possible.

**Comment by brandonzhu09** [comment]
> A few overall comments that may not be immediately relevant to the bugfix:
> 
> 1. First of all, great work on fixing this bug!
> 2. Please add """ docstrings to every function.
> 3. Some of the functions here are helpers, not "views" themselves.  Namely everything from `get_owners` and beyond.  Would it be appropriate to import them from a new `util` module?  I want to keep the `views` as minimal as possible.

That sounds like a good idea! Where would the `util` module go in our file structure?

**Comment by ghost** [comment]
@brandonzhu09  Should it go in `src/evagram/website/backend/`?

**Review by ghost — APPROVED** [review]

**Pull request merged**
